// Generated by https://quicktype.io

export interface infoPagina {
    titulo?: string;
    nombreCorto?: string;
    slogan?: string;
    email?: string;
    Designed?: string;
    facebook?: string;
    facebook2?: string;
    instagram?: string;
    telefono?: string;
    direccion?: string;
    celular?: string;
    horario1?: string;
    horario2?: string;
}


