// Generated by https://quicktype.io

export interface infoCarrusel {
    ruta: string;
    imagenUrl: string;
    titulo: string;
    descripcion: string;
    colorTitulo: string;
    colorDescripcion: string;
}
